import {createServer} from 'node:http';
import {readFile,mkdir,stat} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
// Playwright aus dem Projekt (npm install --no-save playwright) oder aus PLAYWRIGHT_MODULE, z. B. einer globalen Installation.
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
// Screenshots landen in test-results/; TERRA_SCREENSHOTS=docs/screenshots aktualisiert die README-Galerie.
const root=resolve('dist'),results=resolve('test-results'),output=resolve(process.env.TERRA_SCREENSHOTS||'test-results');await mkdir(results,{recursive:true});await mkdir(output,{recursive:true});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.geojson':'application/json','.jpg':'image/jpeg','.svg':'image/svg+xml','.webmanifest':'application/manifest+json','.md':'text/plain'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+'/'))throw Error('Path');res.setHeader('Content-Type',mime[extname(file)]||'application/octet-stream');res.end(await readFile(file));}catch{res.statusCode=404;res.end('Not found');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
let browser;const failures=[],checks=[];
try{
 browser=await chromium.launch({executablePath:process.env.TERRA_CHROMIUM||undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:1800,height:1100},acceptDownloads:true});const page=await context.newPage();page.on('pageerror',e=>failures.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/THREE|WebGL|shader|ReferenceError|TypeError/.test(m.text()))failures.push(m.text());});await page.route('https://earthquake.usgs.gov/**',r=>r.abort());
 await page.goto(origin);await page.waitForFunction(()=>window.terra?.ready);assert.equal(await page.locator('#render-error').isVisible(),false);assert.ok(await page.evaluate(()=>terra.studio.renderer.info.render.triangles)>1000);await page.waitForTimeout(700);await page.screenshot({path:output+'/01-planet.png'});checks.push('Planet loads with rendered geometry and no shader errors');
 await page.getByRole('button',{name:'Erdinneres',exact:true}).click();await page.waitForFunction(()=>terra.state.section==='interior');await page.locator('[data-action=layer][data-id=inner]').click();await page.locator('#explode').fill('60');assert.equal(await page.evaluate(()=>terra.state.layer),'inner');assert.equal(await page.evaluate(()=>terra.state.explode),60);await page.waitForTimeout(700);await page.screenshot({path:output+'/02-erdinneres.png'});checks.push('Interior selection and exploded layers');
 await page.getByRole('button',{name:'Tektonik',exact:true}).click();for(const id of ['subduction','divergence','transform']){await page.locator('[data-action=mechanism][data-id='+id+']').click();assert.equal(await page.evaluate(()=>terra.studio.detailType),id);}await page.locator('[data-action=mechanism][data-id=subduction]').click();await page.waitForTimeout(700);await page.screenshot({path:output+'/03-subduktion.png'});checks.push('All three plate mechanism models');
 await page.getByRole('button',{name:'Zeitreise',exact:true}).click();await page.waitForFunction(()=>terra.studio.paleo.material.map);const first=await page.evaluate(()=>terra.studio.paleo.material.map.image.toDataURL());await page.locator('#epoch').fill('0');await page.waitForFunction(()=>terra.state.age===250&&terra.studio.paleomaps.has(250));await page.waitForTimeout(400);const last=await page.evaluate(()=>terra.studio.paleo.material.map.image.toDataURL());assert.notEqual(first,last);await page.screenshot({path:output+'/04-zeitreise.png'});checks.push('Real reconstruction textures differ between ages');
 await page.getByRole('button',{name:'Erdbeben',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#event-status').textContent.includes('Archivstand'));await page.locator('.event').first().click();assert.ok(await page.evaluate(()=>terra.state.selectedEvent?.id));await page.locator('#toggle-eventDepth').check();await page.locator('#depth-scale').selectOption('8');assert.equal(await page.evaluate(()=>terra.studio.uniforms.uOpacity.value),.48);await page.waitForTimeout(700);await page.screenshot({path:output+'/05-erdbeben.png'});checks.push('USGS failure uses a labeled real archive, event selection and depth scaling');
 await page.getByRole('button',{name:'Expeditionen',exact:true}).click();for(let i=0;i<4;i++)await page.locator('[data-action=step-next]').click();assert.equal(await page.evaluate(()=>terra.studio.detailType),'coal');await page.waitForTimeout(700);await page.screenshot({path:output+'/06-ruhrgebiet.png'});checks.push('Ruhrgebiet expedition traverses globe and layered coal model');
 await page.locator('[data-action=expedition-quiz]').click();await page.locator('[data-answer="0"]').click();assert.equal(await page.locator('.quiz-option.correct').count(),1);assert.equal(await page.locator('#quiz-next').isEnabled(),true);await page.locator('#quiz-next').click();await page.locator('#quiz-dialog [data-close]').click();assert.ok(await page.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem('terra-learning-v1'))).length)>0);checks.push('Quiz feedback and durable local learning');
 await page.getByRole('button',{name:'Planet',exact:true}).click();await page.locator('[data-info=notes]').click();await page.locator('#note').fill('TERRA QA <script> literal note');await page.reload();await page.waitForFunction(()=>window.terra?.ready);await page.locator('[data-info=notes]').click();assert.equal(await page.locator('#note').inputValue(),'TERRA QA <script> literal note');checks.push('Notes survive reload and remain literal text');
 const downloadPromise=page.waitForEvent('download');await page.locator('#capture-portrait').click();const download=await downloadPromise;const destination=resolve(results,'terra-portrait-test.png');await download.saveAs(destination);assert.ok((await stat(destination)).size>30000);checks.push('PNG portrait export produces a nonempty file');
 await page.setViewportSize({width:430,height:932});await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('#mobile-explorer').click();assert.equal(await page.locator('.explorer').isVisible(),true);await page.locator('[data-action=place][data-id=dortmund]').click();assert.equal(await page.locator('.explorer').isVisible(),false);await page.waitForFunction(()=>!document.querySelector('#toast').classList.contains('show'),null,{timeout:6000});await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(500);await page.screenshot({path:output+'/07-mobil.png'});checks.push('Mobile viewport, drawer and touch-sized selection');
 await page.setViewportSize({width:1800,height:1100});await page.locator('#offline-save').click();await page.waitForFunction(()=>document.querySelector('#offline-status').textContent.includes('vollständig offline'),{},{timeout:30000});await context.setOffline(true);await page.reload();await page.waitForFunction(()=>window.terra?.ready);await page.getByRole('button',{name:'Zeitreise',exact:true}).click();await page.locator('#epoch').fill('50');await page.waitForFunction(()=>terra.state.age===200&&terra.studio.paleomaps.has(200));checks.push('Fully cached atlas reloads and loads geology while offline');
 assert.deepEqual(failures,[]);console.log(JSON.stringify({passed:checks,errors:failures,screenshots:output,webMCP:'Unavailable in the installed browser; optional tools feature-detected.'},null,2));
}finally{await browser?.close();await new Promise(r=>server.close(r));}
